server:
  port: 7030

spring:
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
    url: jdbc:${accounting-srv.db.url}
    user: ${accounting-srv.db.user}
    password: ${accounting-srv.db.password}
  r2dbc:
    url: r2dbc:${accounting-srv.db.url}
    username: ${accounting-srv.db.user}
    password: ${accounting-srv.db.password}
    pool:
      initial-size: 5
      max-size: 10
  zipkin:
    enabled: true
    baseUrl: http://localhost:7411/
  logstash:
    host: localhost
    port: 7500    

accounting-srv:
  db:
    url: postgresql://localhost:7031/accountingdb
    user: acUser
    password: acPass
  security:
    jwt:
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhUcCJmSMOfqkKJemWl2/Z25kWVMNfim9KoGjOR+lrKTsvlELNpslyZtwPOhE1P4b2PpU9lmX8Z5y+FsEl0xgUqqnYvQXulA8W6/1N41dBvHXozZUFXvY9/sO6bSlzoUND/tuU7+CGEmqX0ZVDScPboGgfX2O0qgOS9TrdGGwfZ6d4Ujc6HMxgCVIBsuGTKd57Zst1useJB95ca14NI3GXaNG8feXf4MTnaNT7yxLZyNNn9fXvt5qdkfT1qjNDxa39YiU8hlVZ9XPSTakwoFfhZbXN0umNKvoQ4D1kI2nFKOgpPLdrxx9TNIJ2s2lUhqw/PPPaze1nHi3yMqY2Bdu0wIDAQAB