spring:
  zipkin:
    baseUrl: http://zpk:9411/
  logstash:
    host: lgs

menu-srv:
  db:
    host: mongo-db
    port: 27017
    username: acmeUser
    password: "@acmePas2"
    passwordEncoded: "%40acmePas2"
    uri: mongodb://${menu-srv.db.username}:${menu-srv.db.passwordEncoded}@${menu-srv.db.host}:${menu-srv.db.port}/${menu-srv.db.database}