server:
  port: 7050
  forward-headers-strategy: FRAMEWORK

logging:
  level:
    org.springframework: info

spring:
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
    url: ${menu-srv.db.uri}
  data:
    mongodb:
      host: ${menu-srv.db.host}
      port: ${menu-srv.db.port}
      database: ${menu-srv.db.database}
      username: ${menu-srv.db.username}
      password: ${menu-srv.db.password}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  zipkin:
    enabled: true
    baseUrl: http://localhost:7411/
  logstash:
    host: localhost
    port: 7500     

springdoc:
  api-docs:
    path: /${spring.application.name}-swagger/v3/api-docs
  swagger-ui:
    path: /${spring.application.name}-swagger/ui.html
    configUrl: /${spring.application.name}-swagger/v3/api-docs/swagger-config
    url: /${spring.application.name}-swagger/v3/api-docs

menu-srv:
  db:
    host: localhost
    port: 7051
    database: menusrv
    username: mnUser
    password: mnPass
    uri: mongodb://${menu-srv.db.username}:${menu-srv.db.password}@${menu-srv.db.host}:${menu-srv.db.port}/${menu-srv.db.database}
  security:
    jwt:
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhUcCJmSMOfqkKJemWl2/Z25kWVMNfim9KoGjOR+lrKTsvlELNpslyZtwPOhE1P4b2PpU9lmX8Z5y+FsEl0xgUqqnYvQXulA8W6/1N41dBvHXozZUFXvY9/sO6bSlzoUND/tuU7+CGEmqX0ZVDScPboGgfX2O0qgOS9TrdGGwfZ6d4Ujc6HMxgCVIBsuGTKd57Zst1useJB95ca14NI3GXaNG8feXf4MTnaNT7yxLZyNNn9fXvt5qdkfT1qjNDxa39YiU8hlVZ9XPSTakwoFfhZbXN0umNKvoQ4D1kI2nFKOgpPLdrxx9TNIJ2s2lUhqw/PPPaze1nHi3yMqY2Bdu0wIDAQAB