spring:
  rabbitmq:
    host: rmq
    port: 5672
  zipkin:
    baseUrl: http://zpk:9411/
  logstash:
    host: lgs    

pp-srv:
  db:
    url: postgresql://pg-db:5432/ppdb
    user: acmeUser
    password: "@acmePas2"
