spring:
  zipkin:
    baseUrl: http://zpk:9411/
  logstash:
    host: lgs

rf-data-srv:
  db:
    host: mongo-db
    port: 27017
    username: acmeUser
    password: "@acmePas2"
    passwordEncoded: "%40acmePas2"
    uri: mongodb://${rf-data-srv.db.username}:${rf-data-srv.db.passwordEncoded}@${rf-data-srv.db.host}:${rf-data-srv.db.port}/${rf-data-srv.db.database}